### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by alexgleason** [akkera102/02_tiny_depth#1]
Hi, I'm currently in the process of adding license info to all the games in [Erwin's Arduboy repo](http://arduboy.ried.cl/) so people can easily filter out proprietary games. Would you be willing to add an [open source license](https://choosealicense.com/) to your project so I can tag it an open source game in the repo?

Thanks!

**Comment by akkera102** [comment]
hello.

GPL v2
02_tiny_depth
03_tiny_2048
04_tiny_ns_tower
05_tiny_sokoban
06_tiny_asteroids
07_tiny_basic
10_tiny_invader
11_tiny_basic_ab2

LGPL3
08_gamebuino

LGPL( or Later)
09_fxsynth
